### ISSUE TITLE
Store

### ISSUE THREAD

**Issue by fmarzocca** [ZenLiuCN/v3pa#1]
Hi,

congratulations for this interesting mock-up!
If you don't mind, I have a question. My main.vue has to handle a lot of data that I have defined in index.js, for example:

```
data() {
        return {
            ...

            acModes: [
                { label: 'DRY', value: 'Dry' },
                { label: 'COLD', value: 'Cold' },
                { label: 'HEAT', value: 'Heat' },
                { label: 'AUTO', value: 'Auto' },
                { label: 'FANONLY', value: 'Fanonly' }
            ],
            valore1: 50,
            serverTemp: 'No temp measured',
            extCamera: false,
            saloneCamera: false,
            studioCamera: false,
            deumEnable: false,
            myTitle: "Pala Soffitto",
            gardenLights: false,
            ledSaloneTon: '00:00',
            ac: {}

            ....

        }
    }, // --- End of data --- //
```

As you can see, there are also several objects. If I move the html code from the main intex.html into main.vue, I can't get anymore the data. I suppose I need to arrange the store, but I have no idea for this. Could you pls give me a clue?

Thanks

**Comment by ZenLiuCN** [comment]
I don't get what's the point. why write hard coding data in js? try use Http API or load with Fetch. if those will share between pages, use just global variable or use any Store lib should be just fine.
NOTE: the most effective way would be access to an backend to fetch the data.

**Comment by ZenLiuCN** [comment]
I note U have experiences on PHP Python. May just use Global variables with HTTP API to share with other pages  better than adding other Store lib (if it won't be too many data).

**Comment by fmarzocca** [comment]
I fixed this because the app is connected to NodeRed in the backend. So, now the data are handled by NodeRed and sent to the app when needed. 
Thanks for your time!
